http://bugzilla.zimbra.com/show_bug.cgi?id=13908 http://bugzilla.zimbra.com/show_bug.cgi?id=12892 Integrated the following from //depot/FRANK/...: Change 42026 by brian@brian-frank on 2007/01/23 13:09:19
http://bugzilla.zimbra.com/show_bug.cgi?id=13908
http://bugzilla.zimbra.com/show_bug.cgi?id=12892
bug: 13908, 12892
- check free space in /tmp and /opt/zimbra before installing/upgrading
- does not account for mounts below /opt/zimbra

Copied from Perforce
 Change: 42358

diff --git a/rpmconf/Spec/Scripts/InstallationCheck b/rpmconf/Spec/Scripts/InstallationCheck
--- a/rpmconf/Spec/Scripts/InstallationCheck
+++ b/rpmconf/Spec/Scripts/InstallationCheck
@@ -39,4 +39,32 @@ for i in core mta store ldap snmp logger apache spell; do
 		first=2
 	done
 done
+
+GOOD=yes
+echo "Getting for required space..."
+# /tmp must have 1GB
+# /opt/zimbra must have 5GB
+#!/bin/bash
+TMPKB=`df -lk /tmp | tail -1 | awk '{print $4}'`
+AVAIL=$(($TMPKB / 1048576))
+if [ $AVAIL -lt  1 ]; then
+  echo "/tmp must have at least 1GB of availble space to install."
+  echo "${AVAIL}GB is not enough space to install ZCS."
+  GOOD=no
+fi
+
+ZIMBRA=`df -k /opt/zimbra | tail -1 | awk '{print $4}'`
+AVAIL=$(($ZIMBRA / 1048576))
+if [ $AVAIL -lt 5 ]; then
+  echo "/opt/zimbra requires at least 5GB of space to install."
+  echo "${AVAIL}GB is not enough space to install."
+  GOOD=no
+fi
+if [ $GOOD = "no" ]; then
+  echo ""
+  echo "Installation cancelled."
+  echo ""
+  exit 1
+fi
+
 exit 0
